services:
  n8n-main:
    image: ${N8N_IMAGE:-docker.n8n.io/n8nio/n8n:2.22.5}
    restart: unless-stopped
    command: start
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${N8N_POSTGRES_HOST:?}
      DB_POSTGRESDB_PORT: ${N8N_POSTGRES_PORT:-5432}
      DB_POSTGRESDB_DATABASE: ${N8N_POSTGRES_DATABASE:?}
      DB_POSTGRESDB_USER: ${N8N_POSTGRES_USER:?}
      DB_POSTGRESDB_PASSWORD: ${N8N_POSTGRES_PASSWORD:?}
      EXECUTIONS_MODE: queue
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: ${OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS:-true}
      QUEUE_BULL_REDIS_HOST: ${N8N_REDIS_HOST:?}
      QUEUE_BULL_REDIS_PORT: ${N8N_REDIS_PORT:-6379}
      QUEUE_BULL_REDIS_PASSWORD: ${N8N_REDIS_PASSWORD:?}
      QUEUE_BULL_REDIS_DB: ${N8N_REDIS_DB:-0}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY:?}
      N8N_HOST: ${N8N_HOST:?}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-https}
      N8N_PORT: ${N8N_PORT:-5678}
      WEBHOOK_URL: ${WEBHOOK_URL:?}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-America/Sao_Paulo}
    ports:
      - "5678"
    networks:
      - default
      - coolify

networks:
  coolify:
    external: true
